# basic workflow for validating, formatting and generating documentation of terraform projects

name: tf-docs
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    
    - name: terraform-validate
      # You may pin to the exact commit or the version.
      # uses: dflook/terraform-validate@ae1bdb703064ad29842938c230cbb2bfecd155e2
      uses: dflook/terraform-validate@v1.4.1
      with:
        # Path to the terraform configuration
        path: .
    
    - name: terraform-fmt
      # You may pin to the exact commit or the version.
      # uses: dflook/terraform-fmt@80e2fe31f8db99ea0e0e907478e6ce05a99af809
      uses: dflook/terraform-fmt@v1.4.1
      with:
        # Path to the terraform configuration
        path: .

    - name: terraform-docs
      # You may pin to the exact commit or the version.
      # uses: Dirrk/terraform-docs@26b70436ceceba0a62c6b083d67c0796ea89bdeb
      uses: Dirrk/terraform-docs@v1.0.8
      with:
        tf_docs_git_push: true
        tf_docs_output_file: README.md
        tf_docs_output_method: replace
