# basic workflow for validating, formatting and generating documentation of terraform projects

name: terraform preparation
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:

    - uses: actions/checkout@v2
    
    - uses: hashicorp/setup-terraform@v1

    - name: Terraform fmt
      id: fmt
      run: terraform fmt
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Docs
      # You may pin to the exact commit or the version.
      # uses: Dirrk/terraform-docs@26b70436ceceba0a62c6b083d67c0796ea89bdeb
      uses: Dirrk/terraform-docs@v1.0.8
      with:
        tf_docs_git_push: true
        tf_docs_output_file: README.md
        tf_docs_output_method: replace
